//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchemaChekOMS.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XMLSchemaChekOMS.xsd", IsNullable=false)]
public partial class ZPLIST {
    
    private ZP[] zpField;
    
    private string fILENAMEField;
    
    private string oTPRField;
    
    private int oTPRCODField;
    
    private int nRECORDSField;
    
    private System.DateTime dZPField;
    
    public ZPLIST() {
        this.oTPRField = "LPU";
        this.oTPRCODField = 25200;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ZP")]
    public ZP[] ZP {
        get {
            return this.zpField;
        }
        set {
            this.zpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FILENAME {
        get {
            return this.fILENAMEField;
        }
        set {
            this.fILENAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OTPR {
        get {
            return this.oTPRField;
        }
        set {
            this.oTPRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int OTPRCOD {
        get {
            return this.oTPRCODField;
        }
        set {
            this.oTPRCODField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int NRECORDS {
        get {
            return this.nRECORDSField;
        }
        set {
            this.nRECORDSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime DZP {
        get {
            return this.dZPField;
        }
        set {
            this.dZPField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchemaChekOMS.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XMLSchemaChekOMS.xsd", IsNullable=false)]
public partial class ZP {
    
    private PERSON pERSONField;
    
    private DOC dOCField;
    
    private POLIS pOLISField;
    
    private string n_RECField;
    
    /// <remarks/>
    public PERSON PERSON {
        get {
            return this.pERSONField;
        }
        set {
            this.pERSONField = value;
        }
    }
    
    /// <remarks/>
    public DOC DOC {
        get {
            return this.dOCField;
        }
        set {
            this.dOCField = value;
        }
    }
    
    /// <remarks/>
    public POLIS POLIS {
        get {
            return this.pOLISField;
        }
        set {
            this.pOLISField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string N_REC {
        get {
            return this.n_RECField;
        }
        set {
            this.n_RECField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchemaChekOMS.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XMLSchemaChekOMS.xsd", IsNullable=false)]
public partial class PERSON {
    
    private int eNPField;
    
    private string fAMField;
    
    private string imField;
    
    private string otField;
    
    private int wField;
    
    private System.DateTime drField;
    
    public PERSON() {
        this.wField = 2;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ENP {
        get {
            return this.eNPField;
        }
        set {
            this.eNPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FAM {
        get {
            return this.fAMField;
        }
        set {
            this.fAMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IM {
        get {
            return this.imField;
        }
        set {
            this.imField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OT {
        get {
            return this.otField;
        }
        set {
            this.otField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int W {
        get {
            return this.wField;
        }
        set {
            this.wField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime DR {
        get {
            return this.drField;
        }
        set {
            this.drField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchemaChekOMS.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XMLSchemaChekOMS.xsd", IsNullable=false)]
public partial class DOC {
    
    private int dOCTYPEField;
    
    private string dOCSERField;
    
    private string dOCNUMField;
    
    private string mrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int DOCTYPE {
        get {
            return this.dOCTYPEField;
        }
        set {
            this.dOCTYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DOCSER {
        get {
            return this.dOCSERField;
        }
        set {
            this.dOCSERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DOCNUM {
        get {
            return this.dOCNUMField;
        }
        set {
            this.dOCNUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MR {
        get {
            return this.mrField;
        }
        set {
            this.mrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchemaChekOMS.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XMLSchemaChekOMS.xsd", IsNullable=false)]
public partial class POLIS {
    
    private int tPOLField;
    
    private string sPOLField;
    
    private string nPOLField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int TPOL {
        get {
            return this.tPOLField;
        }
        set {
            this.tPOLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SPOL {
        get {
            return this.sPOLField;
        }
        set {
            this.sPOLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NPOL {
        get {
            return this.nPOLField;
        }
        set {
            this.nPOLField = value;
        }
    }
}
